### ISSUE TITLE
[1.7.10] Config settings not working for survival single player...

### ISSUE THREAD

**Issue by ate0ate** [Epoxide-Software/EnchantingPlus#93]
Using Enchanting Plus v3.0.2d in Single Player Survival I am unable to disenchant any items not created by myself nor can I enchant any items with enchantments not usually available to them, despite having changed the following config settings...

B:"Can players disenchant items they have not enchanted?"=true
B:"Disregard item type?"=true

I do not know if these settings work in multiplayer, but they do not in single player. Thanks:)

**Comment by Darkhax** [comment]
Sorry for the late response. There has been a recent change in ownership of the project, and a complete rewrite is being performed. This issue will certainly be fixed in the new release.

**Comment by Darkhax** [comment]
This has been changed in the rewrite. Please let us know if you have this issue in version 4. (not yet released)
