### ISSUE TITLE
EnchantingPlus Compat

### ISSUE THREAD

**Issue by MrLakelynator** [Epoxide-Software/EnchantingPlus#96]
Is there any way to make these two mods work together? The only issue I could think would be that the enchantment ID's aren't under 255, which if it changed in the config it crashes. So any help would be fantastic.

**Comment by MrLakelynator** [comment]
I did some testing with other mods, and it does have to be under 255. So any help about getting the id's down under 255 that would be great.

**Comment by Darkhax** [comment]
I am sorry for the late response. There has been a change in ownership of this mod, and we are currently working on a complete rewrite of the mod. I can assure you that this issue will not exist in the rewrite. I am going to close your issue, however if you have any questions or concerns, don't hesitate to respond here.
