### ISSUE TITLE
repair causes server disconnect and item deleted

### ISSUE THREAD

**Issue by MrKrabat** [Epoxide-Software/EnchantingPlus#97]
hey,
when i try to repair a tool or armor which is very damaged (more than the half) and there are **no bookcases** the client disconnect with an error. The item in the table disappears and is lost.
When i repair something which is just a little (ca. 1/4) damaged it works.

It seems that at some repair level bookcases are required and when the client try to repair without he receives an invalid message causing this problem.

EnchantingPlus 1.7.10-3.0.2d
Minecraft Forge 10.13.4.1448

client and server log:
https://gist.github.com/MrKrabat/2d0f2835926b86f523e9

**Comment by Darkhax** [comment]
Hello there, sorry for the late response. There has been a change in ownership in the mod, and a complete rewrite is currently in progress. This issue will likely be patched by this rewrite. Once we have the project to a stableish place, we will double check that this issue no longer exists.

**Comment by Darkhax** [comment]
This issue does not seem to exist in E+ 4 (Not yet released). If you have this issue on V4 please let us know.
